
[Camera]
distance_in = 48
pupildist_in = 2.5
frontclip_in = 2.00
perspective = true  # Choose Perspective or Planar projection
objscale_in = 2.5

[Object]
nodelist = [
    [ 1.0, 0.0,-0.7071],
    [-1.0, 0.0,-0.7071],
    [ 0.0, 1.0, 0.7071],
    [ 0.0,-1.0, 0.7071],
]

linelist = [
    [0,1],
    [0,2],
    [0,3],
    [1,2],
    [2,3],
    [3,1],
]

init_rot_x = 0.0
init_rot_y = 0.0
init_rot_z = 15.0

frame_rot_x = 0.0
frame_rot_y = 6.0
frame_rot_z = 0.0

num_frames = 60
